version: "3.8"

services:
  superset:
    build:
      context: ./superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "your_secret_key"
    volumes:
      - ./superset:/app/superset_home
    command: ["superset", "run"]

  cubejs:
    build:
      context: ./cubejs
    ports:
      - "4000:4000"
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=duckdb
    volumes:
      - ./cubejs:/cube/conf
    depends_on:
      - duckdb

  duckdb:
    build:
      context: ./duckdb
    volumes:
      - ./duckdb/data:/data
    command: ["duckdb", "/data/my_database.db"]


